### ISSUE TITLE
Main.css integration with research.php

### ISSUE THREAD

**Issue by rozenberg4christ** [alphaX86/it-site#9]
https://github.com/alphaX86/it-site/blob/031caee932ca76382fd37047d4b3fd082844ebda/CSS/main.css#L3

### A bit of styling integration 

@shankuroko  I guess this line is causing some errors to my code.

1) Consider setting up a lower value. (I guess that will affect other parts of code too.)

2) So I will also try to change my code .

**If 1st option is not good to go then close this issue.**

**Comment by alphaX86** [comment]
It's being fixed... Will consider that
